name: BACKEND CI

on:
  push:
    branches:
    - main
    paths:
    - 'backend/**'
  pull_request:
    paths:
    - 'backend/**'
    - '.github/workflows/backend_ci.yml'

permissions:
  contents: read
  actions: read

jobs:
  go-test:
    name: GO TEST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Run tests
        working-directory: ./backend
        run: go test -v ./... -cover 
  
  go-lint:
    name: GO LINT
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Run tests
        working-directory: ./backend
        run: go test -v ./... -cover 
  name: BACKEND CI

on:
  push:
    branches:
    - main
    paths:
    - 'backend/**'
  pull_request:
    paths:
    - 'backend/**'
    - '.github/workflows/backend_ci.yml'

permissions:
  contents: read
  actions: read

jobs:
  go-test:
    name: GO TEST
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Run tests
        working-directory: ./backend
        run: go test -v ./... -cover 
  
  go-lint:
    name: GO LINT
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Run tests
        working-directory: ./backend
        run: go test -v ./... -cover 
